services:
  redis:
    image: redis:8-alpine
    restart: always
    ports:
      - "6380:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  asset-watcher:
    container_name: asset-watcher
    build:
      dockerfile: node.Dockerfile
      context: .
    restart: always
    volumes:
      - ./app/static:/home/node/app/static

  web:
    container_name: test-a-provider-data-ui
    build:
      context: .
      args:
        REQUIREMENTS_FILE: "requirements-development.txt"
      target: development
    restart: always
    environment:
      - SECRET_KEY=CHANGE_ME
      - FLASK_RUN_PORT=8020
      - SENTRY_DSN=${SENTRY_DSN:-}
      - REDIS_URL=redis://redis:6379/0
      - ENTRA_ID_SKIP_AUTH=True
      - PDA_USE_MOCK_API=${PDA_USE_MOCK_API:-True}
      - PDA_URL=${PDA_URL:-https://mock-api.com}
      - PDA_ENVIRONMENT=${PDA_ENVIRONMENT:-Mock}
      - PDA_API_KEY=${PDA_API_KEY:-mock-api-key}
    ports:
      - "8020:8020"
    volumes:
      - ./app:/home/app/test-a-provider-data-ui/app
      - ./tests:/home/app/test-a-provider-data-ui/tests
    depends_on:
      - redis

volumes:
  redis_data:
