environment: "staging"
replicaCount: 1

ingress:
  enabled: true
  host: "laa-test-a-provider-data-ui-staging.cloud-platform.service.justice.gov.uk"

whitelist:
  enabled: true

pdb:
  enabled: true
  minAvailable: 1

envVars:
  PDA_USE_MOCK_API:
    value: "True"
  PDA_ENVIRONMENT:
    value: "Mock"
