name: Feature Branch

run-name: Feature - ${{ github.head_ref || github.ref_name }}

on:
  push:
    branches-ignore:
      - main
  pull_request:
    types:
      - reopened

jobs:
  test:
     name: Test
     uses: ./.github/workflows/test.yml

  static-analysis:
    name: Static Analysis
    needs: test
    uses: ./.github/workflows/static-analysis.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}